[package]
name = "st2r-compiler"
version = "0.1.0"
authors = ["St2r <St2r@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
